name:          SV Code Guide by @arkmuntasser
description:   Standards for developing flexible, durable, and sustainable HTML, CSS, and JavaScript.
url:           https://arkmuntasser.github.io/code-guide

markdown:      rdiscount
permalink:     pretty
pygments:      true
